version: '3.8'

services:
  backend:
    build: ./backend
    container_name: concord-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: concord-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://backend:3001
    depends_on:
      - backend

